<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Games" data-toc-modified-id="Games-0.1">Games</a></span></li><li><span><a href="#nicks" data-toc-modified-id="nicks-0.2">nicks</a></span></li><li><span><a href="#team_names" data-toc-modified-id="team_names-0.3">team_names</a></span></li></ul></li><li><span><a href="#Generating-dataset" data-toc-modified-id="Generating-dataset-1">Generating dataset</a></span><ul class="toc-item"><li><span><a href="#generating-random-items" data-toc-modified-id="generating-random-items-1.1">generating random items</a></span></li><li><span><a href="#game---team" data-toc-modified-id="game---team-1.2">game - team</a></span></li><li><span><a href="#people-teams" data-toc-modified-id="people-teams-1.3">people-teams</a></span></li><li><span><a href="#people-team-game" data-toc-modified-id="people-team-game-1.4">people-team-game</a></span></li><li><span><a href="#datetimes" data-toc-modified-id="datetimes-1.5">datetimes</a></span></li><li><span><a href="#gameplays" data-toc-modified-id="gameplays-1.6">gameplays</a></span></li></ul></li></ul></div>

In [1]:
import pandas as pd

from datetime import datetime, timedelta

import numpy as np

In [2]:
def pp(start: datetime, end: datetime, n: int):
    # based on https://stackoverflow.com/questions/50559078/generating-random-dates-within-a-given-range-in-pandas
    start_u = int(start.timestamp())
    end_u = int(end.timestamp())
    return pd.DatetimeIndex((np.random.randint(start_u, end_u, n, dtype=np.int64)).view('M8[s]'))

In [3]:
now = datetime.utcnow()
one_year_ago = datetime.utcnow() - timedelta(days=365)

pp(start=one_year_ago, end=now, n=100)

DatetimeIndex(['2020-07-05 06:38:13', '2020-10-14 20:18:36',
               '2021-01-09 06:17:23', '2021-05-04 07:12:18',
               '2020-11-21 08:11:15', '2021-04-02 04:44:07',
               '2021-05-24 07:55:11', '2020-11-18 03:59:32',
               '2021-05-30 12:21:30', '2020-12-25 01:59:58',
               '2020-08-11 16:53:31', '2020-12-21 00:14:11',
               '2020-11-04 21:31:25', '2021-01-05 23:06:35',
               '2021-03-19 11:44:59', '2020-10-23 17:39:59',
               '2021-06-01 00:09:17', '2020-11-10 08:55:34',
               '2020-08-18 17:25:32', '2021-03-03 11:57:20',
               '2020-10-20 12:34:03', '2021-06-03 16:23:59',
               '2021-03-10 21:25:12', '2020-12-30 16:28:09',
               '2021-01-21 10:55:29', '2020-08-21 09:38:09',
               '2021-02-23 05:04:57', '2020-11-10 02:44:57',
               '2020-08-19 15:52:15', '2020-11-17 00:14:11',
               '2020-08-26 12:57:29', '2020-10-28 23:13:51',
               '2020-07-31 07:50:50', '2020-10-20 00:00:31',
               '2021-05-04 21:42:54', '2021-04-27 07:39:26',
               '2020-08-08 05:47:43', '2020-07-14 21:08:54',
               '2020-09-18 16:05:02', '2020-11-05 11:01:43',
               '2020-08-07 14:24:38', '2020-08-28 00:32:11',
               '2020-08-23 19:44:08', '2020-08-26 14:57:55',
               '2020-12-11 23:45:36', '2020-10-13 03:46:43',
               '2021-02-10 03:23:05', '2020-09-18 19:59:50',
               '2020-08-09 10:56:55', '2021-03-05 03:08:52',
               '2021-01-10 10:01:24', '2020-12-04 14:34:54',
               '2020-09-01 18:25:59', '2021-01-10 15:14:55',
               '2020-12-03 02:00:41', '2021-05-23 12:43:29',
               '2020-12-11 03:07:04', '2020-11-14 09:56:49',
               '2021-03-10 02:57:21', '2021-03-20 17:33:51',
               '2021-05-03 12:55:22', '2020-11-15 12:00:07',
               '2020-08-08 19:22:07', '2020-08-07 16:53:09',
               '2020-06-23 19:26:57', '2021-01-22 20:31:23',
               '2021-04-07 20:39:03', '2020-08-22 19:36:17',
               '2020-10-21 09:15:56', '2020-09-28 04:49:51',
               '2020-11-23 06:03:24', '2021-06-09 16:57:55',
               '2021-04-04 04:40:37', '2020-10-15 01:07:06',
               '2021-01-03 01:01:52', '2020-11-20 12:32:35',
               '2020-09-15 07:05:40', '2020-12-21 08:38:58',
               '2021-01-27 22:10:36', '2020-09-23 21:11:16',
               '2020-07-10 01:54:20', '2020-07-10 02:36:12',
               '2021-03-16 23:52:06', '2021-05-22 00:27:13',
               '2020-09-22 13:31:50', '2020-10-05 23:18:36',
               '2020-10-13 01:30:05', '2020-11-07 09:44:10',
               '2020-07-15 18:42:57', '2020-11-05 06:23:45',
               '2021-02-28 19:37:29', '2020-11-10 19:17:34',
               '2020-07-09 23:30:13', '2021-04-15 18:38:04',
               '2021-02-05 07:55:05', '2020-08-25 17:12:19',
               '2020-11-16 12:49:48', '2021-02-19 13:12:47',
               '2020-08-03 23:17:01', '2020-08-03 05:53:36'],
              dtype='datetime64[ns]', freq=None)

### Games

In [4]:
data = pd.read_html('https://en.wikipedia.org/wiki/List_of_most-played_video_games_by_player_count')

In [5]:
games_df = data[4]
games_df

,Game,Number,As of,Business model,Release date,Publisher(s),Ref.
0,PlayerUnknown's Battlegrounds,"1,037 million[a]",March 2021,Pay-to-play/free-to-play,"December 20, 2017",Krafton / Tencent,[b]
1,CrossFire,"1,000 million",February 2020,Free-to-play,"May 3, 2007",Smilegate / Tencent,[3]
2,Dungeon Fighter Online,700 million,May 2020,Free-to-play,August 2005,Nexon / Tencent,[4]
3,QQ Speed / GKART / Speed Drifters,700 million[a],January 2020,Free-to-play,"January 23, 2008",Tencent / Garena,[5]
4,Minecraft,600 million[a][c],November 2020,Pay-to-play/free-to-play,"November 18, 2011",Mojang / NetEase[c],[6]
...,...,...,...,...,...,...,...
94,Free Realms,10 million registered accounts,April 2018,Free-to-play,"April 28, 2009",Sony Online Entertainment,[30]
95,H1Z1,10 million,June 2018,Free-to-play,"February 28, 2018",Daybreak Game Company,[75]
96,Robocraft,10 million owners on Steam[k],July 2018,Free-to-play,"August 24, 2017",Freejam Games,[2]
97,Ark: Survival Evolved,10 million[a],November 2017,Pay-to-play,"August 29, 2017",Studio Wildcard,[76]
98,Star Wars Jedi: Fallen Order,10 million,May 2020,Pay-to-play,"November 15, 2019",Electronic Arts,[77]

In [14]:
games_df.to_csv('data/games_df.csv', index=False)

In [15]:
game_names = games_df.Game.to_list()
game_names

["PlayerUnknown's Battlegrounds",
 'CrossFire',
 'Dungeon Fighter Online',
 'QQ Speed / GKART / Speed Drifters',
 'Minecraft',
 'Pac-Man Doodle',
 'Candy Crush Saga',
 'Among Us',
 'Microsoft Solitaire',
 'Mini World',
 'Crazyracing Kartrider',
 'Fortnite',
 'Fantasy Westward Journey',
 'RuneScape',
 'Rules of Survival',
 'Roblox',
 'Dragon Nest',
 'MapleStory',
 'Tetris',
 'Animal Jam',
 'World of Tanks',
 'Grand Theft Auto V',
 'The Legend of Mir 3',
 'League of Legends',
 'World of Warcraft',
 'CityVille',
 'Happy Farm',
 'Scions of Fate',
 'The Sims Social',
 'Zhengtu',
 'Microsoft Solitaire Collection',
 'Hearthstone',
 'Apex Legends',
 'Call of Duty: Warzone',
 'FarmVille',
 'Westward Journey Online II',
 'Ragnarok Online',
 'Moshi Monsters',
 'Yu-Gi-Oh! Duel Links',
 'Dragon Oath',
 'Rocket League',
 'Dofus',
 'Adopt Me!',
 'Flyff',
 'Overwatch',
 'Lineage',
 'Perfect World',
 'Team Fortress 2',
 "Tom Clancy's Rainbow Six Siege",
 'Warframe',
 'Counter-Strike: Global Offensive',
 'FarmVille 2',
 'The Sims 4',
 'Drakensang Online',
 'Teamfight Tactics',
 'Evony',
 'FIFA 18',
 'Pac-Man',
 'Black Desert Online',
 'FIFA 17',
 'FIFA 16',
 'GetAmped',
 'Metal Slug Defense',
 'TERA',
 'Unturned',
 'FIFA 21',
 'Street Fighter II',
 'Call of Duty: WWII',
 'Left 4 Dead 2',
 'Sudden Attack',
 'Nexus: The Kingdom of the Winds',
 'Final Fantasy XIV',
 'Mabinogi',
 'DC Universe Online',
 'Shadowverse',
 'Blade & Soul',
 'Payday 2',
 'Farm Town',
 'The Last of Us Remastered',
 'osu!',
 'Doom',
 'For Honor',
 'Trove',
 'Puyopuyo!! Quest Arcade',
 'Lineage II',
 'Paladins',
 'Battlefield 4',
 'The Elder Scrolls Online',
 'Dota 2',
 'Call of Duty: Ghosts',
 'FIFA 19',
 'Guild Wars 2',
 'Forza Horizon 3',
 'Star Wars: The Old Republic',
 'Free Realms',
 'H1Z1',
 'Robocraft',
 'Ark: Survival Evolved',
 'Star Wars Jedi: Fallen Order']

### nicks

In [16]:
names_dfs = pd.read_html('https://www.ssa.gov/oact/babynames/decades/century.html')

In [17]:
names_dfs[0]

    Unnamed: 0_level_0                                              Males  \
                  Rank                                               Name
0                  1.0                                              James
1                  2.0                                             Robert
2                  3.0                                               John
3                  4.0                                            Michael
4                  5.0                                            William
..                 ...                                                ...
96                97.0                                              Louis
97                98.0                                              Bobby
98                99.0                                             Philip
99               100.0                                             Johnny
100                NaN  Source: 100% sample based on Social Security c...

                                                        \
                                                Number
0                                              4700229
1                                              4455696
2                                              4453807
3                                              4335919
4                                              3564276
..                                                 ...
96                                              314537
97                                              313403
98                                              313385
99                                              308289
100  Source: 100% sample based on Social Security c...

                                               Females  \
                                                  Name
0                                                 Mary
1                                             Patricia
2                                             Jennifer
3                                                Linda
4                                            Elizabeth
..                                                 ...
96                                           Charlotte
97                                                Rose
98                                              Alexis
99                                               Kayla
100  Source: 100% sample based on Social Security c...


                                                Number
0                                              3196385
1                                              1558407
2                                              1468377
3                                              1448303
4                                              1420377
..                                                 ...
96                                              347772
97                                              344656
98                                              340587
99                                              340511
100  Source: 100% sample based on Social Security c...

[101 rows x 5 columns]

In [18]:
names_df = names_dfs[0].iloc[:-1]
names_df

   Unnamed: 0_level_0    Males             Females
                 Rank     Name   Number       Name   Number
0                 1.0    James  4700229       Mary  3196385
1                 2.0   Robert  4455696   Patricia  1558407
2                 3.0     John  4453807   Jennifer  1468377
3                 4.0  Michael  4335919      Linda  1448303
4                 5.0  William  3564276  Elizabeth  1420377
..                ...      ...      ...        ...      ...
95               96.0   Elijah   316573   Isabella   354245
96               97.0    Louis   314537  Charlotte   347772
97               98.0    Bobby   313403       Rose   344656
98               99.0   Philip   313385     Alexis   340587
99              100.0   Johnny   308289      Kayla   340511

[100 rows x 5 columns]

In [19]:
names_df.to_csv('data/names_df.csv', index=False)

In [20]:
names_list = names_df.Males.Name.to_list() + names_df.Females.Name.to_list()
names_list = [n.lower() for n in names_list]
names_list

['james',
 'robert',
 'john',
 'michael',
 'william',
 'david',
 'richard',
 'joseph',
 'thomas',
 'charles',
 'christopher',
 'daniel',
 'matthew',
 'anthony',
 'mark',
 'donald',
 'steven',
 'paul',
 'andrew',
 'joshua',
 'kenneth',
 'kevin',
 'brian',
 'george',
 'edward',
 'ronald',
 'timothy',
 'jason',
 'jeffrey',
 'ryan',
 'jacob',
 'gary',
 'nicholas',
 'eric',
 'jonathan',
 'stephen',
 'larry',
 'justin',
 'scott',
 'brandon',
 'benjamin',
 'samuel',
 'gregory',
 'frank',
 'alexander',
 'raymond',
 'patrick',
 'jack',
 'dennis',
 'jerry',
 'tyler',
 'aaron',
 'jose',
 'adam',
 'henry',
 'nathan',
 'douglas',
 'zachary',
 'peter',
 'kyle',
 'walter',
 'ethan',
 'jeremy',
 'harold',
 'keith',
 'christian',
 'roger',
 'noah',
 'gerald',
 'carl',
 'terry',
 'sean',
 'austin',
 'arthur',
 'lawrence',
 'jesse',
 'dylan',
 'bryan',
 'joe',
 'jordan',
 'billy',
 'bruce',
 'albert',
 'willie',
 'gabriel',
 'logan',
 'alan',
 'juan',
 'wayne',
 'roy',
 'ralph',
 'randy',
 'eugene',
 'vincent',
 'russell',
 'elijah',
 'louis',
 'bobby',
 'philip',
 'johnny',
 'mary',
 'patricia',
 'jennifer',
 'linda',
 'elizabeth',
 'barbara',
 'susan',
 'jessica',
 'sarah',
 'karen',
 'nancy',
 'lisa',
 'betty',
 'margaret',
 'sandra',
 'ashley',
 'kimberly',
 'emily',
 'donna',
 'michelle',
 'dorothy',
 'carol',
 'amanda',
 'melissa',
 'deborah',
 'stephanie',
 'rebecca',
 'sharon',
 'laura',
 'cynthia',
 'kathleen',
 'amy',
 'shirley',
 'angela',
 'helen',
 'anna',
 'brenda',
 'pamela',
 'nicole',
 'emma',
 'samantha',
 'katherine',
 'christine',
 'debra',
 'rachel',
 'catherine',
 'carolyn',
 'janet',
 'ruth',
 'maria',
 'heather',
 'diane',
 'virginia',
 'julie',
 'joyce',
 'victoria',
 'olivia',
 'kelly',
 'christina',
 'lauren',
 'joan',
 'evelyn',
 'judith',
 'megan',
 'cheryl',
 'andrea',
 'hannah',
 'martha',
 'jacqueline',
 'frances',
 'gloria',
 'ann',
 'teresa',
 'kathryn',
 'sara',
 'janice',
 'jean',
 'alice',
 'madison',
 'doris',
 'abigail',
 'julia',
 'judy',
 'grace',
 'denise',
 'amber',
 'marilyn',
 'beverly',
 'danielle',
 'theresa',
 'sophia',
 'marie',
 'diana',
 'brittany',
 'natalie',
 'isabella',
 'charlotte',
 'rose',
 'alexis',
 'kayla']

### team_names

In [21]:
import requests
from lxml import html

In [22]:
response = requests.get('https://ideasfornames.com/cool-unique-team-names-perfect-for-your-group/')

In [23]:
tree = html.fromstring(response.content)

In [24]:
lis = tree.xpath('//article[@class="post-content entry-content"]//ul/li//text()')
lis

['Share',
 'Tweet',
 'Pin',
 'A Team',
 'All Stars',
 'Amigos',
 'Avengers',
 'Bannermen',
 'Best of the Best',
 'Bosses',
 'Champions',
 'Crew',
 'Dominators',
 'Dream Team',
 'Elite',
 'Force',
 'Goal Diggers',
 'Heatwave',
 'Hot Shots',
 'Hustle',
 'Icons',
 'Justice League',
 'Legends',
 'Lightning',
 'Maniacs',
 'Masters',
 'Monarchy',
 'Naturals',
 'Ninjas',
 'Outliers',
 'Peak Performers',
 'Power',
 'Rebels',
 'Revolution',
 'Ringmasters',
 'Rule Breakers',
 'Shakedown',
 'Squad',
 'Titans',
 'Tribe',
 'United',
 'Vikings',
 'Warriors',
 'Wolf Pack',
 'Aces',
 'Assassins',
 'Armada',
 'Bandits',
 'Blaze',
 'Brute Force',
 'Chaos',
 'Chosen Ones',
 'Conquerors',
 'Defenders',
 'Empire',
 'Extreme',
 'Fury',
 'Gladiators',
 'High Voltage',
 'Hitmen',
 'Inferno',
 'Intimidators',
 'Kingsmen',
 'Lethal Weapons',
 'Mafia',
 'Matrix',
 'No Fear',
 'Outlaws',
 'Pistols',
 'Pulverizers',
 'Rage',
 'Renegades',
 'Riot',
 'Rumble',
 'Samurais',
 'Stealth',
 'Terminators',
 'Trouble Makers',
 'Unbeatable',
 'Venom',
 'Weapons of Mass Destruction',
 'Wrecking Crew',
 'Adrenaline',
 'Alliance',
 'Arsenal',
 'Badasses',
 'Blitz',
 'Brigade',
 'Calvary',
 'Collective',
 'Dothraki',
 'End Game',
 'Fuego',
 'Guardians',
 'Heathens',
 'Horsepower',
 'Impact',
 'Ironmen',
 'Keep It 100',
 'Magic',
 'Mystery',
 'No Sympathy',
 'Obliterators',
 'Phenomenon',
 'Phoenix',
 'Rampage',
 'Regulators',
 'Rough Necks',
 'Savage Joes',
 'Status Quo',
 'Thrashers',
 'Unstoppable',
 'Vicious',
 'Wild Things',
 'Your Worst Nightmare',
 'A Team Has No Name',
 'We Tried',
 'Enter Team Name Here',
 'No Shame',
 'Mediocrity At Its Best',
 'Savage and Average',
 'Wasted Potential',
 'Best Team Name',
 'We Showed Up',
 'Mandatory Attendance',
 'Boom Shaka Laka',
 'Newbies',
 'Mandatory Fun',
 'Noobs',
 'Lovable and Lazy',
 'Our Uniforms Match',
 'Minimum Wagers',
 'Couch Potatoes',
 'Waiting For Naptime',
 'Creative Team Name',
 'Shoes or Lose',
 'Make Teams Great Again',
 'Another Team Name',
 'Cranky Yankees',
 'Movers and Shakers',
 'Heartbreakers',
 'One More Team Name',
 '2nd Choice of Team Name',
 'Coffee Addicts',
 'Cheers For Beers',
 'Tea Spillers',
 'Boozy Bunch',
 'Will Work For Food',
 'Winos',
 'Always Hungry',
 'All Hungover',
 'Praise Cheeses',
 'Cereal Killers',
 'Snack Attack',
 'Addicted to Cake',
 'Cupcakes',
 'Stud Muffins',
 'No Slice Left Behind',
 'Sugar Babies',
 'Sugar Daddies',
 'Kids R Us',
 'Teenage Dream',
 'Plenty of Twenties',
 'The Roaring Twenties',
 'Young Bucks',
 'Dirty Thirty',
 'Oh Lordy, We’re Forty',
 '50 Shades of Age',
 'Old Timers',
 'Eighties Babies',
 'Baby Boomers',
 'Millennials',
 'Generation X',
 'Generation Z',
 '0% Risk',
 '100 percent',
 '49ers',
 '76ers',
 '8th Wonders of World',
 '99 percenters',
 'Administration',
 'Admirals',
 'Adrenaline',
 'Advocates',
 'Aeros',
 'Aggies',
 'Aliens',
 'Alliance',
 'Alpha Team',
 'Alphas',
 'Ambassadors',
 'American Patriots',
 'Americans',
 'Angels',
 'Animals',
 'Annihilators',
 'Anteaters',
 'Apocalypse',
 'Archers',
 'Around The Horn',
 'Arrows',
 'Asteroids',
 'Astronomic',
 'Astros',
 'Athletics',
 'Avalanche',
 'Aztecs',
 'Bachelors\xa0',
 'Bad Boys\xa0',
 'Bad Boys 4 Life',
 'Bad News Bears',
 'Bad to The Bone',
 'Bane of Your Existence\xa0',
 'Barbarians',
 'Barnstormers',
 'Barons',
 'Bats',
 'Battle Buddies',
 'Battle Hawks',
 'Bay Bears',
 'Bean Counters',
 'Bearcats',
 'Bears',
 'Beasts',
 'Bees',
 'Belles',
 'Bengals',
 'Berets',
 'Big Bats',
 'Big Horns',
 'Bills',
 'Bisons',
 'Black Knights',
 'Black Panthers',
 'Black Widows',
 'Blackhawks',
 'Blades',
 'Blast',
 'Blasters',
 'Blazers',
 'Blitzkrieg',
 'Blossoms',
 'Blue Angels',
 'Blue Birds',
 'Blue Collars',
 'Blue Jackets',
 'Blue Jays',
 'Blue Whales',
 'Blues',
 'Bobcats',
 'Bolts',
 'Bombers',
 'Bookworms',
 'Boomers',
 'Bots',
 'Boulders',
 'Braves',
 'Brewers',
 'Brewmaster',
 'Broncos',
 'Browns',
 'Bruins',
 'Buccaneers',
 'Bucks',
 'Buffaloes',
 'Builders',
 'Bulldogs',
 'Bulldogs',
 'Bulletproof',
 'Bullets',
 'Bullfighters',
 'Bulls',
 'Butchers',
 'Canucks',
 'Capitals',
 'Captains',
 'Captivators',
 'Cardinals',
 'Cavaliers',
 'Celtics',
 'Challengers',
 'Chameleons',
 'Chaos',
 'Chargers',
 'Chasers',
 'Chiefs',
 'CIA',
 'Circus Animals',
 'Claws',
 'Clippers',
 'Cobras',
 'Code Black\xa0',
 'Code Red',
 'Collision Course',
 'Colts',
 'Comets',
 'Compadres',
 'Connected',
 'Cosmos',
 'Cougars',
 'Cowboys',
 'Coyotes',
 'Crafty Crew',
 'Crazy 8’s',
 'Crunch',
 'Crusaders',
 'Crush',
 'Cubs',
 'Curve',
 'Cyclones',
 'Dangers',
 'Darkside',
 'Deal Makers',
 'Deathwish',
 'Decision-makers',
 'Deep Pockets',
 'Delinquents',
 'Demolition Crew',
 'Desert Storm',
 'Desperados',
 'Destroyers',
 'Devils',
 'Diamondbacks',
 'Diplomats',
 'Divas',
 'Divide and Conquer\xa0',
 'Dodgers',
 'Dolphins',
 'Dragons',
 'Dream Crushers',
 'Drifters\xa0',
 'Drones',
 'Dropping Bombs',
 'Duchesses',
 'Ducks',
 'Dukes',
 'Dynamix',
 'Dynamo',
 'Dynomite',
 'Eagles',
 'Earthquakes',
 'Eliminators',
 'Empowered',
 'Enforcers\xa0',
 'Enigma',
 'Entrepreneurs',
 'Eruption',
 'Eskimos',
 'Esquires',
 'Evolution',
 'Executioners',
 'Expendables',
 'Explorers',
 'Explosion',
 'Exterminators\xa0',
 'Fairies',
 'Falcons',
 'Fast And Furious',
 'Felons',
 'Fighters',
 'Fighting Irish',
 'Fire',
 'Fire Starters',
 'Firebirds',
 'Fireflies',
 'Firing Squad',
 'Firm',
 'Fisher Cats',
 'Fixers',
 'Flames',
 'Flash',
 'Flight',
 'Flight Crew',
 'Flyers',
 'Flying Dutchmen',
 'Flying Monkeys',
 'Foundation',
 'Four Horsemen',
 'Foxes',
 'Freaks',
 'Frontline',
 'Full Effect',
 'Full Out\xa0',
 'Fusion',
 'G-Force',
 'Galaxy',
 'Gamecocks',
 'Gargoyles',
 'Gatling Guns',
 'Gators',
 'Generals',
 'Gentlemen',
 'Ghost Riders\xa0',
 'Ghosts',
 'Giants',
 'Goblins',
 'Godfathers',
 'Gold Rush',
 'Golden Eagles\xa0',
 'Gophers',
 'Gorillas',
 'Grave Diggers',
 'Gravity',
 'Greyhounds',
 'Griffins',
 'Grizzlies',
 'Growlers',
 'Gulls',
 'Gunners',
 'Guns for Hire\xa0',
 'Hammerheads',
 'Hawkeyes',
 'Hawks',
 'Head Hunters',
 'Heat',
 'Hell’s Angels',
 'Hellraisers',
 'Herons',
 'High Altitude',
 'High Flyers',
 'High Rollers',
 'Hillbillies',
 'Hit Team',
 'Hitters',
 'Hive',
 'Home Runners\xa0',
 'Homers',
 'Homies',
 'Hoodlums',
 'Hooks',
 'Hoosiers',
 'Hornets',
 'Hurricanes',
 'Huskies',
 'Hustlers',
 'Icehogs',
 'Ice Wall',
 'Iconic',
 'In Style',
 'Incredibles',
 'Independence',
 'Indians',
 'Infantry',
 'Influencers',
 'Insurgents\xa0',
 'Invaders',
 'Islanders',
 'Jackrabbits',
 'Jaguars',
 'Jalapenos',
 'Jawbreakers',
 'Jayhawks',
 'Jazz',
 'Jets',
 'Jocks',
 'Jokers',
 'Judges',
 'Juiced',
 'Jungle Kings',
 'Justice Bringers',
 'Kangeroos',
 'Kickers',
 'Killer Whales',
 'Kingdom',
 'Kingpins',
 'Kings',
 'Kittens',
 'Knights',
 'Koalas',
 'Kryptonite',
 'Ladies',
 'Lady Killers',
 'Lake Hawks',
 'Lakers',
 'Laser Beams',
 'Leaders',
 'Legacy',
 'Leopards',
 'Life Savers',
 'Lilas',
 'Lions',
 'Lobos',
 'Longhorns',
 'Lords',
 'Lost Boys',
 'Lumberjacks',
 'Mad Bombers',
 'Mad Men',
 'Magicians',
 'Majors',
 'Mammoths',
 'Maple Leafs',
 'Marauders',
 'Mariners',
 'Marines',
 'Marlins',
 'Marshalls',
 'Masons',
 'Matadors',
 'Mavericks',
 'Mean Green',
 'Mean Machine',
 'Men In Black\xa0',
 'Men on a Mission',
 'Mercenaries',
 'Mermaids',
 'Meteors',
 'Mets',
 'MI6',
 'Mighty Ducks',
 'Minutemen',
 'Mob',
 'Monarchs',
 'Money Makers',
 'Monsters',
 'Moose',
 'Mountaineers',
 'Mud Dogs',
 'Mud Hens',
 'Musketeers',
 'Mustangs',
 'Nationals',
 'Neck Breakers',
 'Nerds',
 'Nets',
 'Nirvana',
 'No Mercy',
 'No Pain, No Gain',
 'No Rules\xa0',
 'No Way Out',
 'Northern Lights',
 'Novastars',
 'Nuggets',
 'Occupiers',
 'Oilers',
 'Olympians',
 'Only Contenders',
 'Orcas',
 'Orediggers',
 'Orioles',
 'Otters',
 'Over Achievers',
 'Owls',
 'Pacers',
 'Packers',
 'Padres',
 'Pandas',
 'Panthers',
 'Patriots',
 'Peacekeepers',
 'Peacocks',
 'Penguins',
 'Perfecto’s',
 'Phantoms',
 'Phillies',
 'Pilots',
 'Pimps',
 'Pioneers',
 'Piranhas',
 'Pirates',
 'Pistons',
 'Pitbulls',
 'Players',
 'Polar Bears',
 'Power House',
 'Prairie Wolves',
 'Predators',
 'Presidents',
 'Priceless',
 'Princes',
 'Princesses',
 'Prodigies',
 'Professionals',
 'Prophets',
 'Prowlers',
 'Punishers',
 'Puppet Masters',
 'Pups',
 'Pythons',
 'Quake',
 'Quicksilvers',
 'Racers',
 'Radicals',
 'Ragin Cajuns',
 'Raging Bulls',
 'Raiders',
 'RailHawks',
 'Rams',
 'Rangers',
 'Rapids',
 'Raptors',
 'Rattlesnakes',
 'Ravens',
 'Rays',
 'Razorbacks',
 'Reapers',
 'Rebellion',
 'Red Bulls',
 'Red Raiders',
 'Red Rapids',
 'Red Rovers',
 'Red Sox',
 'Red Wings',
 'Redbirds',
 'Redhawks',
 'Reds',
 'Redskins',
 'Republic',
 'Rescue Team',
 'Retrievers',
 'Rhinos',
 'Rhythm',
 'Riders',
 'Ringleaders',
 'Rip Tide',
 'River Cats',
 'River Hounds',
 'River Rats',
 'Rivermen',
 'Robots',
 'Rock Cats',
 'Rock Stars',
 'Rockers',
 'Rocket Launchers',
 'Rocketmen',
 'Rockets',
 'Rockies',
 'Rocks',
 'Roses',
 'Rough Riders',
 'Royals',
 'Royalty',
 'Saboteurs',
 'Sabres',
 'Sailors',
 'Saints',
 'Sand Sharks',
 'Savages',
 'Scappers',
 'Scorpions',
 'Scrappers',
 'Screamin Demons',
 'Sea Dogs',
 'Sea Lions',
 'Seabirds',
 'Seahawks',
 'Security',
 'Senators',
 'Shadows',
 'Shameless',
 'Shapeshifters',
 'Sharks',
 'Sharks in Suits',
 'Sharp Shooters',
 'Shield',
 'Shock and Awe',
 'Shocks',
 'Shoguns',
 'Shooting Stars',
 'Showboats',
 'Showrunners',
 'Sicarios',
 'Sinners',
 'Skull Crushers',
 'Skywalkers',
 'Slam',
 'Slayers\xa0',
 'Sledgehammers',
 'Sliders',
 'Sluggers',
 'Snipers',
 'Soldiers',
 'Soul Takers',
 'Sounders',
 'Sounds',
 'Spartans',
 'Special K’s',
 'Speed Demons',
 'Spider Monkeys',
 'Spiders',
 'Spies',
 'Spurs',
 'Squadron',
 'Stallions',
 'Stampede',
 'Stampeders',
 'Stars',
 'Statesmen',
 'Steelers',
 'Stingrays',
 'Stone Crushers',
 'Storm',
 'Storm Breakers',
 'Storm Chasers',
 'Straight Shooters',
 'Strangers',
 'Strikers',
 'Suits',
 'Sultans',
 'Suns',
 'Super Heroes',
 'Super Humans',
 'Super Sonics',
 'Surf',
 'Swag',
 'Swagger',
 'Sweet Heat',
 'Sweethearts',
 'Take No Prisoners',
 'Tar Heels',
 'Tater Tots',
 'Tech Attack',
 'Terrapins',
 'Terrorizers',
 'Texans',
 'Thunder',
 'Thunder Bolts',
 'Thunderbirds',
 'Tidal Waves',
 'Tide',
 'Tides',
 'Tigers',
 'Timbers',
 'Timberwolves',
 'TKOs',
 'Tomcats',
 'Torches',
 'Toreros',
 'Tornadoes',
 'Toros',
 'Trail Blazers',
 'Trappers',
 'Travelers',
 'Tritons',
 'Trojans',
 'Tsunamis',
 'Turtleheads',
 'Twins',
 'Unicorns',
 'Union',
 'Unknowns',
 'Unlimited',
 'Untouchables',
 'Usual Suspects',
 'Vampires',
 'Vandals',
 'Vaqueros',
 'Veterans',
 'Vigilantes',
 'Viking Raiders',
 'Vipers',
 'Volcanoes',
 'Voyagers',
 'Vultures',
 'Wanderers',
 'War Eagles',
 'Warlocks',
 'Warmongers',
 'Watchers',
 'Waves',
 'Weed Wackers',
 'Whales',
 'Whammers',
 'Whirlwinds',
 'White Collars',
 'White Sox',
 'White Walkers',
 'Whitecaps',
 'Wild',
 'Wildcats',
 'Wildebeests',
 'Witches',
 'Wizards',
 'Wolverines',
 'Wolves',
 'Wombats',
 'Workers Bees',
 'Wraiths',
 'X Men\xa0',
 'Y',
 'ankees',
 'Yellow Jackets',
 'Zeniths',
 'Zephyrs',
 'Zombies',
 'Zoo Animals',
 '600+ Best Baseball And Softball Team Names That Hit It Out Of The Park',
 '200+ Funny Baseball And Softball Team Names That Are Sure To Be A Hit',
 '175+ Best Dance Team Names That Are Perfect For Your Group',
 'Share',
 'Tweet',
 'Pin',
 '« ',
 '200+ Funny Baseball And Softball Team Names That Are Sure To Be A Hit',
 '175+ Best Dance Team Names That Are Perfect For Your Group',
 ' »',
 '\r\n              ',
 '\r\n            ',
 '101+ Cool Nicknames For Girls That She Will Love',
 '\r\n    ',
 '\r\n              ',
 '\r\n            ',
 '175+ Cutest Baby Girl Names That Have Charming Nicknames You’ll Love',
 '\r\n    ',
 '\r\n              ',
 '\r\n            ',
 '250+ Outstanding Orange Cat Names Perfect For Your Ginger Kitty',
 '\r\n    ']

In [25]:
lis.index('A Team')

3

In [26]:
lis.index('Zoo Animals')

785

In [30]:
teams = lis[3:786]
teams

['A Team',
 'All Stars',
 'Amigos',
 'Avengers',
 'Bannermen',
 'Best of the Best',
 'Bosses',
 'Champions',
 'Crew',
 'Dominators',
 'Dream Team',
 'Elite',
 'Force',
 'Goal Diggers',
 'Heatwave',
 'Hot Shots',
 'Hustle',
 'Icons',
 'Justice League',
 'Legends',
 'Lightning',
 'Maniacs',
 'Masters',
 'Monarchy',
 'Naturals',
 'Ninjas',
 'Outliers',
 'Peak Performers',
 'Power',
 'Rebels',
 'Revolution',
 'Ringmasters',
 'Rule Breakers',
 'Shakedown',
 'Squad',
 'Titans',
 'Tribe',
 'United',
 'Vikings',
 'Warriors',
 'Wolf Pack',
 'Aces',
 'Assassins',
 'Armada',
 'Bandits',
 'Blaze',
 'Brute Force',
 'Chaos',
 'Chosen Ones',
 'Conquerors',
 'Defenders',
 'Empire',
 'Extreme',
 'Fury',
 'Gladiators',
 'High Voltage',
 'Hitmen',
 'Inferno',
 'Intimidators',
 'Kingsmen',
 'Lethal Weapons',
 'Mafia',
 'Matrix',
 'No Fear',
 'Outlaws',
 'Pistols',
 'Pulverizers',
 'Rage',
 'Renegades',
 'Riot',
 'Rumble',
 'Samurais',
 'Stealth',
 'Terminators',
 'Trouble Makers',
 'Unbeatable',
 'Venom',
 'Weapons of Mass Destruction',
 'Wrecking Crew',
 'Adrenaline',
 'Alliance',
 'Arsenal',
 'Badasses',
 'Blitz',
 'Brigade',
 'Calvary',
 'Collective',
 'Dothraki',
 'End Game',
 'Fuego',
 'Guardians',
 'Heathens',
 'Horsepower',
 'Impact',
 'Ironmen',
 'Keep It 100',
 'Magic',
 'Mystery',
 'No Sympathy',
 'Obliterators',
 'Phenomenon',
 'Phoenix',
 'Rampage',
 'Regulators',
 'Rough Necks',
 'Savage Joes',
 'Status Quo',
 'Thrashers',
 'Unstoppable',
 'Vicious',
 'Wild Things',
 'Your Worst Nightmare',
 'A Team Has No Name',
 'We Tried',
 'Enter Team Name Here',
 'No Shame',
 'Mediocrity At Its Best',
 'Savage and Average',
 'Wasted Potential',
 'Best Team Name',
 'We Showed Up',
 'Mandatory Attendance',
 'Boom Shaka Laka',
 'Newbies',
 'Mandatory Fun',
 'Noobs',
 'Lovable and Lazy',
 'Our Uniforms Match',
 'Minimum Wagers',
 'Couch Potatoes',
 'Waiting For Naptime',
 'Creative Team Name',
 'Shoes or Lose',
 'Make Teams Great Again',
 'Another Team Name',
 'Cranky Yankees',
 'Movers and Shakers',
 'Heartbreakers',
 'One More Team Name',
 '2nd Choice of Team Name',
 'Coffee Addicts',
 'Cheers For Beers',
 'Tea Spillers',
 'Boozy Bunch',
 'Will Work For Food',
 'Winos',
 'Always Hungry',
 'All Hungover',
 'Praise Cheeses',
 'Cereal Killers',
 'Snack Attack',
 'Addicted to Cake',
 'Cupcakes',
 'Stud Muffins',
 'No Slice Left Behind',
 'Sugar Babies',
 'Sugar Daddies',
 'Kids R Us',
 'Teenage Dream',
 'Plenty of Twenties',
 'The Roaring Twenties',
 'Young Bucks',
 'Dirty Thirty',
 'Oh Lordy, We’re Forty',
 '50 Shades of Age',
 'Old Timers',
 'Eighties Babies',
 'Baby Boomers',
 'Millennials',
 'Generation X',
 'Generation Z',
 '0% Risk',
 '100 percent',
 '49ers',
 '76ers',
 '8th Wonders of World',
 '99 percenters',
 'Administration',
 'Admirals',
 'Adrenaline',
 'Advocates',
 'Aeros',
 'Aggies',
 'Aliens',
 'Alliance',
 'Alpha Team',
 'Alphas',
 'Ambassadors',
 'American Patriots',
 'Americans',
 'Angels',
 'Animals',
 'Annihilators',
 'Anteaters',
 'Apocalypse',
 'Archers',
 'Around The Horn',
 'Arrows',
 'Asteroids',
 'Astronomic',
 'Astros',
 'Athletics',
 'Avalanche',
 'Aztecs',
 'Bachelors\xa0',
 'Bad Boys\xa0',
 'Bad Boys 4 Life',
 'Bad News Bears',
 'Bad to The Bone',
 'Bane of Your Existence\xa0',
 'Barbarians',
 'Barnstormers',
 'Barons',
 'Bats',
 'Battle Buddies',
 'Battle Hawks',
 'Bay Bears',
 'Bean Counters',
 'Bearcats',
 'Bears',
 'Beasts',
 'Bees',
 'Belles',
 'Bengals',
 'Berets',
 'Big Bats',
 'Big Horns',
 'Bills',
 'Bisons',
 'Black Knights',
 'Black Panthers',
 'Black Widows',
 'Blackhawks',
 'Blades',
 'Blast',
 'Blasters',
 'Blazers',
 'Blitzkrieg',
 'Blossoms',
 'Blue Angels',
 'Blue Birds',
 'Blue Collars',
 'Blue Jackets',
 'Blue Jays',
 'Blue Whales',
 'Blues',
 'Bobcats',
 'Bolts',
 'Bombers',
 'Bookworms',
 'Boomers',
 'Bots',
 'Boulders',
 'Braves',
 'Brewers',
 'Brewmaster',
 'Broncos',
 'Browns',
 'Bruins',
 'Buccaneers',
 'Bucks',
 'Buffaloes',
 'Builders',
 'Bulldogs',
 'Bulldogs',
 'Bulletproof',
 'Bullets',
 'Bullfighters',
 'Bulls',
 'Butchers',
 'Canucks',
 'Capitals',
 'Captains',
 'Captivators',
 'Cardinals',
 'Cavaliers',
 'Celtics',
 'Challengers',
 'Chameleons',
 'Chaos',
 'Chargers',
 'Chasers',
 'Chiefs',
 'CIA',
 'Circus Animals',
 'Claws',
 'Clippers',
 'Cobras',
 'Code Black\xa0',
 'Code Red',
 'Collision Course',
 'Colts',
 'Comets',
 'Compadres',
 'Connected',
 'Cosmos',
 'Cougars',
 'Cowboys',
 'Coyotes',
 'Crafty Crew',
 'Crazy 8’s',
 'Crunch',
 'Crusaders',
 'Crush',
 'Cubs',
 'Curve',
 'Cyclones',
 'Dangers',
 'Darkside',
 'Deal Makers',
 'Deathwish',
 'Decision-makers',
 'Deep Pockets',
 'Delinquents',
 'Demolition Crew',
 'Desert Storm',
 'Desperados',
 'Destroyers',
 'Devils',
 'Diamondbacks',
 'Diplomats',
 'Divas',
 'Divide and Conquer\xa0',
 'Dodgers',
 'Dolphins',
 'Dragons',
 'Dream Crushers',
 'Drifters\xa0',
 'Drones',
 'Dropping Bombs',
 'Duchesses',
 'Ducks',
 'Dukes',
 'Dynamix',
 'Dynamo',
 'Dynomite',
 'Eagles',
 'Earthquakes',
 'Eliminators',
 'Empowered',
 'Enforcers\xa0',
 'Enigma',
 'Entrepreneurs',
 'Eruption',
 'Eskimos',
 'Esquires',
 'Evolution',
 'Executioners',
 'Expendables',
 'Explorers',
 'Explosion',
 'Exterminators\xa0',
 'Fairies',
 'Falcons',
 'Fast And Furious',
 'Felons',
 'Fighters',
 'Fighting Irish',
 'Fire',
 'Fire Starters',
 'Firebirds',
 'Fireflies',
 'Firing Squad',
 'Firm',
 'Fisher Cats',
 'Fixers',
 'Flames',
 'Flash',
 'Flight',
 'Flight Crew',
 'Flyers',
 'Flying Dutchmen',
 'Flying Monkeys',
 'Foundation',
 'Four Horsemen',
 'Foxes',
 'Freaks',
 'Frontline',
 'Full Effect',
 'Full Out\xa0',
 'Fusion',
 'G-Force',
 'Galaxy',
 'Gamecocks',
 'Gargoyles',
 'Gatling Guns',
 'Gators',
 'Generals',
 'Gentlemen',
 'Ghost Riders\xa0',
 'Ghosts',
 'Giants',
 'Goblins',
 'Godfathers',
 'Gold Rush',
 'Golden Eagles\xa0',
 'Gophers',
 'Gorillas',
 'Grave Diggers',
 'Gravity',
 'Greyhounds',
 'Griffins',
 'Grizzlies',
 'Growlers',
 'Gulls',
 'Gunners',
 'Guns for Hire\xa0',
 'Hammerheads',
 'Hawkeyes',
 'Hawks',
 'Head Hunters',
 'Heat',
 'Hell’s Angels',
 'Hellraisers',
 'Herons',
 'High Altitude',
 'High Flyers',
 'High Rollers',
 'Hillbillies',
 'Hit Team',
 'Hitters',
 'Hive',
 'Home Runners\xa0',
 'Homers',
 'Homies',
 'Hoodlums',
 'Hooks',
 'Hoosiers',
 'Hornets',
 'Hurricanes',
 'Huskies',
 'Hustlers',
 'Icehogs',
 'Ice Wall',
 'Iconic',
 'In Style',
 'Incredibles',
 'Independence',
 'Indians',
 'Infantry',
 'Influencers',
 'Insurgents\xa0',
 'Invaders',
 'Islanders',
 'Jackrabbits',
 'Jaguars',
 'Jalapenos',
 'Jawbreakers',
 'Jayhawks',
 'Jazz',
 'Jets',
 'Jocks',
 'Jokers',
 'Judges',
 'Juiced',
 'Jungle Kings',
 'Justice Bringers',
 'Kangeroos',
 'Kickers',
 'Killer Whales',
 'Kingdom',
 'Kingpins',
 'Kings',
 'Kittens',
 'Knights',
 'Koalas',
 'Kryptonite',
 'Ladies',
 'Lady Killers',
 'Lake Hawks',
 'Lakers',
 'Laser Beams',
 'Leaders',
 'Legacy',
 'Leopards',
 'Life Savers',
 'Lilas',
 'Lions',
 'Lobos',
 'Longhorns',
 'Lords',
 'Lost Boys',
 'Lumberjacks',
 'Mad Bombers',
 'Mad Men',
 'Magicians',
 'Majors',
 'Mammoths',
 'Maple Leafs',
 'Marauders',
 'Mariners',
 'Marines',
 'Marlins',
 'Marshalls',
 'Masons',
 'Matadors',
 'Mavericks',
 'Mean Green',
 'Mean Machine',
 'Men In Black\xa0',
 'Men on a Mission',
 'Mercenaries',
 'Mermaids',
 'Meteors',
 'Mets',
 'MI6',
 'Mighty Ducks',
 'Minutemen',
 'Mob',
 'Monarchs',
 'Money Makers',
 'Monsters',
 'Moose',
 'Mountaineers',
 'Mud Dogs',
 'Mud Hens',
 'Musketeers',
 'Mustangs',
 'Nationals',
 'Neck Breakers',
 'Nerds',
 'Nets',
 'Nirvana',
 'No Mercy',
 'No Pain, No Gain',
 'No Rules\xa0',
 'No Way Out',
 'Northern Lights',
 'Novastars',
 'Nuggets',
 'Occupiers',
 'Oilers',
 'Olympians',
 'Only Contenders',
 'Orcas',
 'Orediggers',
 'Orioles',
 'Otters',
 'Over Achievers',
 'Owls',
 'Pacers',
 'Packers',
 'Padres',
 'Pandas',
 'Panthers',
 'Patriots',
 'Peacekeepers',
 'Peacocks',
 'Penguins',
 'Perfecto’s',
 'Phantoms',
 'Phillies',
 'Pilots',
 'Pimps',
 'Pioneers',
 'Piranhas',
 'Pirates',
 'Pistons',
 'Pitbulls',
 'Players',
 'Polar Bears',
 'Power House',
 'Prairie Wolves',
 'Predators',
 'Presidents',
 'Priceless',
 'Princes',
 'Princesses',
 'Prodigies',
 'Professionals',
 'Prophets',
 'Prowlers',
 'Punishers',
 'Puppet Masters',
 'Pups',
 'Pythons',
 'Quake',
 'Quicksilvers',
 'Racers',
 'Radicals',
 'Ragin Cajuns',
 'Raging Bulls',
 'Raiders',
 'RailHawks',
 'Rams',
 'Rangers',
 'Rapids',
 'Raptors',
 'Rattlesnakes',
 'Ravens',
 'Rays',
 'Razorbacks',
 'Reapers',
 'Rebellion',
 'Red Bulls',
 'Red Raiders',
 'Red Rapids',
 'Red Rovers',
 'Red Sox',
 'Red Wings',
 'Redbirds',
 'Redhawks',
 'Reds',
 'Redskins',
 'Republic',
 'Rescue Team',
 'Retrievers',
 'Rhinos',
 'Rhythm',
 'Riders',
 'Ringleaders',
 'Rip Tide',
 'River Cats',
 'River Hounds',
 'River Rats',
 'Rivermen',
 'Robots',
 'Rock Cats',
 'Rock Stars',
 'Rockers',
 'Rocket Launchers',
 'Rocketmen',
 'Rockets',
 'Rockies',
 'Rocks',
 'Roses',
 'Rough Riders',
 'Royals',
 'Royalty',
 'Saboteurs',
 'Sabres',
 'Sailors',
 'Saints',
 'Sand Sharks',
 'Savages',
 'Scappers',
 'Scorpions',
 'Scrappers',
 'Screamin Demons',
 'Sea Dogs',
 'Sea Lions',
 'Seabirds',
 'Seahawks',
 'Security',
 'Senators',
 'Shadows',
 'Shameless',
 'Shapeshifters',
 'Sharks',
 'Sharks in Suits',
 'Sharp Shooters',
 'Shield',
 'Shock and Awe',
 'Shocks',
 'Shoguns',
 'Shooting Stars',
 'Showboats',
 'Showrunners',
 'Sicarios',
 'Sinners',
 'Skull Crushers',
 'Skywalkers',
 'Slam',
 'Slayers\xa0',
 'Sledgehammers',
 'Sliders',
 'Sluggers',
 'Snipers',
 'Soldiers',
 'Soul Takers',
 'Sounders',
 'Sounds',
 'Spartans',
 'Special K’s',
 'Speed Demons',
 'Spider Monkeys',
 'Spiders',
 'Spies',
 'Spurs',
 'Squadron',
 'Stallions',
 'Stampede',
 'Stampeders',
 'Stars',
 'Statesmen',
 'Steelers',
 'Stingrays',
 'Stone Crushers',
 'Storm',
 'Storm Breakers',
 'Storm Chasers',
 'Straight Shooters',
 'Strangers',
 'Strikers',
 'Suits',
 'Sultans',
 'Suns',
 'Super Heroes',
 'Super Humans',
 'Super Sonics',
 'Surf',
 'Swag',
 'Swagger',
 'Sweet Heat',
 'Sweethearts',
 'Take No Prisoners',
 'Tar Heels',
 'Tater Tots',
 'Tech Attack',
 'Terrapins',
 'Terrorizers',
 'Texans',
 'Thunder',
 'Thunder Bolts',
 'Thunderbirds',
 'Tidal Waves',
 'Tide',
 'Tides',
 'Tigers',
 'Timbers',
 'Timberwolves',
 'TKOs',
 'Tomcats',
 'Torches',
 'Toreros',
 'Tornadoes',
 'Toros',
 'Trail Blazers',
 'Trappers',
 'Travelers',
 'Tritons',
 'Trojans',
 'Tsunamis',
 'Turtleheads',
 'Twins',
 'Unicorns',
 'Union',
 'Unknowns',
 'Unlimited',
 'Untouchables',
 'Usual Suspects',
 'Vampires',
 'Vandals',
 'Vaqueros',
 'Veterans',
 'Vigilantes',
 'Viking Raiders',
 'Vipers',
 'Volcanoes',
 'Voyagers',
 'Vultures',
 'Wanderers',
 'War Eagles',
 'Warlocks',
 'Warmongers',
 'Watchers',
 'Waves',
 'Weed Wackers',
 'Whales',
 'Whammers',
 'Whirlwinds',
 'White Collars',
 'White Sox',
 'White Walkers',
 'Whitecaps',
 'Wild',
 'Wildcats',
 'Wildebeests',
 'Witches',
 'Wizards',
 'Wolverines',
 'Wolves',
 'Wombats',
 'Workers Bees',
 'Wraiths',
 'X Men\xa0',
 'Y',
 'ankees',
 'Yellow Jackets',
 'Zeniths',
 'Zephyrs',
 'Zombies',
 'Zoo Animals']

In [31]:
with open('data/teams.txt', 'w') as f:
    f.write('\n'.join(teams))

## Generating dataset

In [51]:
num_players = 10000
num_teams = num_players // 20

num_players / num_teams

20.0

### generating random items

In [52]:
import random

In [53]:
def generate_random(input_vals: list, n: int, add_num_end: bool = True):
    names = random.choices(input_vals, k=n)
    if add_num_end:
        result = [f'{n}_{i}' for i, n in enumerate(names)]
    else:
        result = names
    return result

generate_random(teams, 10)

['Yellow Jackets_0',
 'Kingsmen_1',
 'Zombies_2',
 'Orediggers_3',
 'Sea Dogs_4',
 'No Way Out_5',
 'Unlimited_6',
 'Rivermen_7',
 'Home Runners\xa0_8',
 'Phantoms_9']

### game - team

In [54]:
all_teams = generate_random(teams, num_teams)
all_teams

['Blue Whales_0',
 'Wolf Pack_1',
 'Boulders_2',
 'Hell’s Angels_3',
 'Tech Attack_4',
 'Athletics_5',
 '0% Risk_6',
 'Wrecking Crew_7',
 'Ghost Riders\xa0_8',
 'Blitz_9',
 'Phenomenon_10',
 'Ironmen_11',
 'Cereal Killers_12',
 'Beasts_13',
 'Marlins_14',
 'Trojans_15',
 'Jungle Kings_16',
 'River Rats_17',
 'Aggies_18',
 'Strikers_19',
 'Wolverines_20',
 'Twins_21',
 'Monsters_22',
 'Soldiers_23',
 'Juiced_24',
 'Zephyrs_25',
 'Flash_26',
 'Guardians_27',
 'Huskies_28',
 'Tritons_29',
 '2nd Choice of Team Name_30',
 'Felons_31',
 'Monsters_32',
 'Captains_33',
 'Ravens_34',
 'Blue Collars_35',
 'Boomers_36',
 'Tea Spillers_37',
 'Enforcers\xa0_38',
 'Kids R Us_39',
 'Sicarios_40',
 'Venom_41',
 'War Eagles_42',
 'Rule Breakers_43',
 'Slayers\xa0_44',
 'Bullfighters_45',
 'Players_46',
 'Captivators_47',
 'Witches_48',
 'Hoosiers_49',
 'Sugar Daddies_50',
 'Praise Cheeses_51',
 'Take No Prisoners_52',
 'Hillbillies_53',
 'Enter Team Name Here_54',
 'Slam_55',
 'Barbarians_56',
 'Sledgehammers_57',
 'The Roaring Twenties_58',
 'Old Timers_59',
 'Storm_60',
 'Goblins_61',
 'Elite_62',
 'Puppet Masters_63',
 'Blue Whales_64',
 'Blitzkrieg_65',
 'Mountaineers_66',
 'Hellraisers_67',
 'Jayhawks_68',
 'Growlers_69',
 'Mercenaries_70',
 'Administration_71',
 'Dynamo_72',
 'Hillbillies_73',
 'Saboteurs_74',
 'Dominators_75',
 'Peacocks_76',
 'Rocket Launchers_77',
 'Lethal Weapons_78',
 'Bad News Bears_79',
 'ankees_80',
 'Pistons_81',
 'Exterminators\xa0_82',
 'No Fear_83',
 'Surf_84',
 'Hurricanes_85',
 'Riders_86',
 'Blue Whales_87',
 'Titans_88',
 'Mad Men_89',
 'Explorers_90',
 'Destroyers_91',
 'Aliens_92',
 'Sharp Shooters_93',
 'Administration_94',
 'Hillbillies_95',
 'Enigma_96',
 'Oilers_97',
 'Influencers_98',
 'Lobos_99',
 'Maniacs_100',
 'Raiders_101',
 'Crafty Crew_102',
 'Fast And Furious_103',
 'Men on a Mission_104',
 'Shoguns_105',
 'Firm_106',
 'Lightning_107',
 'We Showed Up_108',
 'Coyotes_109',
 'Mad Bombers_110',
 'Angels_111',
 'Polar Bears_112',
 'Ducks_113',
 'Tech Attack_114',
 'Iconic_115',
 'United_116',
 'Mean Machine_117',
 'Sultans_118',
 'Dukes_119',
 'Kryptonite_120',
 'Lovable and Lazy_121',
 'Stampede_122',
 'Sweethearts_123',
 'Cranky Yankees_124',
 'Kangeroos_125',
 'Sugar Daddies_126',
 'No Pain, No Gain_127',
 'Vaqueros_128',
 'Bengals_129',
 'Duchesses_130',
 'Dangers_131',
 'Princes_132',
 'Armada_133',
 'Bats_134',
 'Patriots_135',
 'Vigilantes_136',
 'Bats_137',
 'Aztecs_138',
 'Crusaders_139',
 'Rangers_140',
 'Rage_141',
 'Ninjas_142',
 'Braves_143',
 'Sicarios_144',
 'Tritons_145',
 'Ringleaders_146',
 'Baby Boomers_147',
 'Veterans_148',
 'Sliders_149',
 'Golden Eagles\xa0_150',
 'Raging Bulls_151',
 'Sounds_152',
 'Crunch_153',
 'Force_154',
 'White Collars_155',
 'Timbers_156',
 'Broncos_157',
 'Arsenal_158',
 'Matadors_159',
 'Newbies_160',
 'Goal Diggers_161',
 'Tornadoes_162',
 'Sharp Shooters_163',
 'Horsepower_164',
 'Vultures_165',
 'Rattlesnakes_166',
 'Gators_167',
 'Phoenix_168',
 'Code Black\xa0_169',
 'Spartans_170',
 'Mediocrity At Its Best_171',
 'Mean Green_172',
 'Super Humans_173',
 'Blue Angels_174',
 'Redhawks_175',
 'Raging Bulls_176',
 'Reds_177',
 'Twins_178',
 'Golden Eagles\xa0_179',
 'Shooting Stars_180',
 'Storm Chasers_181',
 'Robots_182',
 'Sinners_183',
 'Rock Cats_184',
 'Straight Shooters_185',
 'Asteroids_186',
 'Whitecaps_187',
 'Blasters_188',
 'Matrix_189',
 'Phantoms_190',
 'Bears_191',
 'Boulders_192',
 'Dream Team_193',
 'Keep It 100_194',
 'Goal Diggers_195',
 'Ladies_196',
 'Sharks_197',
 'Herons_198',
 'Jokers_199',
 'Mercenaries_200',
 'Galaxy_201',
 'Firebirds_202',
 'Seabirds_203',
 'Novastars_204',
 'Old Timers_205',
 'Fury_206',
 'Marshalls_207',
 'A Team_208',
 'Heatwave_209',
 'Magicians_210',
 'Surf_211',
 'Rockies_212',
 'Royalty_213',
 'Tide_214',
 'Stars_215',
 'Texans_216',
 'Black Knights_217',
 'No Sympathy_218',
 'Shock and Awe_219',
 'Rampage_220',
 'Barons_221',
 'Untouchables_222',
 'Homies_223',
 'Status Quo_224',
 'Monarchs_225',
 'Wanderers_226',
 'Fireflies_227',
 'Chaos_228',
 'Movers and Shakers_229',
 'Foxes_230',
 '100 percent_231',
 'Weed Wackers_232',
 'Challengers_233',
 'Occupiers_234',
 'Blue Whales_235',
 'Dropping Bombs_236',
 'Rampage_237',
 'Flying Dutchmen_238',
 'Kids R Us_239',
 'Bears_240',
 'Blaze_241',
 'Shoes or Lose_242',
 'Priceless_243',
 'Hammerheads_244',
 'Colts_245',
 'Whirlwinds_246',
 'Armada_247',
 'Hit Team_248',
 'Seabirds_249',
 'Texans_250',
 'Pioneers_251',
 'Majors_252',
 'Men on a Mission_253',
 'Griffins_254',
 'Rocketmen_255',
 'Movers and Shakers_256',
 'Our Uniforms Match_257',
 'Rip Tide_258',
 'Crazy 8’s_259',
 'Blast_260',
 'Browns_261',
 'Dragons_262',
 'Cyclones_263',
 'Bullets_264',
 'Mystery_265',
 'Snack Attack_266',
 'Rocketmen_267',
 'Butchers_268',
 'Gulls_269',
 'Sea Lions_270',
 'Enigma_271',
 'Warlocks_272',
 'No Way Out_273',
 'Pilots_274',
 'Barnstormers_275',
 'Builders_276',
 'Money Makers_277',
 'Storm_278',
 'Justice League_279',
 'Bulletproof_280',
 'Cupcakes_281',
 'No Slice Left Behind_282',
 'Drones_283',
 'Crush_284',
 'Straight Shooters_285',
 'Dodgers_286',
 'Stone Crushers_287',
 'Olympians_288',
 'Extreme_289',
 'Rockers_290',
 'Kickers_291',
 'Claws_292',
 'Bots_293',
 'Weed Wackers_294',
 'Obliterators_295',
 'Kickers_296',
 'Lions_297',
 'Grizzlies_298',
 'Expendables_299',
 'Aliens_300',
 'Apocalypse_301',
 'Jets_302',
 'Barbarians_303',
 'Wombats_304',
 'Predators_305',
 'Esquires_306',
 'Kryptonite_307',
 'Diamondbacks_308',
 'Unknowns_309',
 'Flyers_310',
 'White Collars_311',
 'Priceless_312',
 'Lost Boys_313',
 'Mad Bombers_314',
 'Regulators_315',
 'Sand Sharks_316',
 'Spider Monkeys_317',
 'Clippers_318',
 'Revolution_319',
 'Empire_320',
 'Weapons of Mass Destruction_321',
 'Orioles_322',
 'White Collars_323',
 'Otters_324',
 'Retrievers_325',
 'Matadors_326',
 'Squadron_327',
 'Trail Blazers_328',
 'Predators_329',
 'Will Work For Food_330',
 'Ninjas_331',
 'Bean Counters_332',
 'Unstoppable_333',
 'Rock Cats_334',
 'Drifters\xa0_335',
 'Marlins_336',
 'Matrix_337',
 'Longhorns_338',
 'Men In Black\xa0_339',
 'All Hungover_340',
 'Justice Bringers_341',
 'Prowlers_342',
 'Code Black\xa0_343',
 'Juiced_344',
 'Firing Squad_345',
 'Chasers_346',
 'Sugar Daddies_347',
 'Drones_348',
 'Pirates_349',
 'Men In Black\xa0_350',
 'Gulls_351',
 'Texans_352',
 'Noobs_353',
 'Bruins_354',
 'Black Widows_355',
 'Marauders_356',
 'Coyotes_357',
 'Fuego_358',
 'Screamin Demons_359',
 'Veterans_360',
 'Incredibles_361',
 'Titans_362',
 'Lethal Weapons_363',
 'Red Wings_364',
 'Dangers_365',
 'Shoes or Lose_366',
 'Leaders_367',
 'Black Knights_368',
 'Dream Team_369',
 'Rebellion_370',
 'Orioles_371',
 'Leopards_372',
 'Pistols_373',
 'War Eagles_374',
 'Challengers_375',
 'Barons_376',
 'Riot_377',
 'Grave Diggers_378',
 'Explorers_379',
 'Boomers_380',
 'Tidal Waves_381',
 'Rockets_382',
 'Sea Lions_383',
 '8th Wonders of World_384',
 'Snack Attack_385',
 'Sluggers_386',
 'Eskimos_387',
 'Hoosiers_388',
 'G-Force_389',
 'Explorers_390',
 'Generals_391',
 'Icehogs_392',
 'Blaze_393',
 'No Mercy_394',
 'Bucks_395',
 'No Slice Left Behind_396',
 'Rebellion_397',
 'Bad to The Bone_398',
 'Nirvana_399',
 'Tide_400',
 'Over Achievers_401',
 'Arsenal_402',
 'Ironmen_403',
 'Spies_404',
 'Regulators_405',
 'Blitz_406',
 'Raiders_407',
 'Peak Performers_408',
 'Sicarios_409',
 'Sluggers_410',
 'Enter Team Name Here_411',
 'Vipers_412',
 'Blossoms_413',
 'Arsenal_414',
 'No Slice Left Behind_415',
 'Seabirds_416',
 'Ringmasters_417',
 'Deal Makers_418',
 'Showrunners_419',
 'Will Work For Food_420',
 'Thunder_421',
 'Mean Machine_422',
 'Galaxy_423',
 'Redhawks_424',
 'Shameless_425',
 'Koalas_426',
 'Unstoppable_427',
 'Avengers_428',
 'Shock and Awe_429',
 'Red Bulls_430',
 'Dynamix_431',
 'One More Team Name_432',
 'Rams_433',
 'Stud Muffins_434',
 'Gatling Guns_435',
 'Braves_436',
 'Ice Wall_437',
 'Alphas_438',
 'Canucks_439',
 'Gargoyles_440',
 'Northern Lights_441',
 'Maniacs_442',
 'Teenage Dream_443',
 'Redbirds_444',
 'Wanderers_445',
 'Marshalls_446',
 'Screamin Demons_447',
 'One More Team Name_448',
 'Mandatory Fun_449',
 'Goblins_450',
 'Creative Team Name_451',
 'Magicians_452',
 'Darkside_453',
 'Gorillas_454',
 'Volcanoes_455',
 'Roses_456',
 'Yellow Jackets_457',
 'Bulldogs_458',
 'Super Heroes_459',
 'Advocates_460',
 'Flight Crew_461',
 'Pimps_462',
 'Enigma_463',
 'Invaders_464',
 'Jocks_465',
 'No Slice Left Behind_466',
 'River Hounds_467',
 'Swagger_468',
 'Spurs_469',
 'Jalapenos_470',
 'Unlimited_471',
 'Lethal Weapons_472',
 'Huskies_473',
 'Raptors_474',
 'Gamecocks_475',
 'Best Team Name_476',
 'Orioles_477',
 'Bolts_478',
 'Noobs_479',
 'Venom_480',
 'Hit Team_481',
 'Drifters\xa0_482',
 'Head Hunters_483',
 'Knights_484',
 'Rough Necks_485',
 'Owls_486',
 'Rhythm_487',
 'Oilers_488',
 'Rock Cats_489',
 'Black Widows_490',
 'Hit Team_491',
 'Entrepreneurs_492',
 'Saboteurs_493',
 'Flight_494',
 'Big Horns_495',
 'Shock and Awe_496',
 'Astronomic_497',
 'Delinquents_498',
 'Stealth_499']

In [55]:
team_game_df = pd.DataFrame({'team': all_teams})
team_game_df['game'] = generate_random(game_names, n=num_teams, add_num_end=False)
team_game_df

                  team                   game
0        Blue Whales_0            Free Realms
1          Wolf Pack_1                   osu!
2           Boulders_2                Pac-Man
3      Hell’s Angels_3                FIFA 17
4        Tech Attack_4            Shadowverse
..                 ...                    ...
495      Big Horns_495                   osu!
496  Shock and Awe_496  Call of Duty: Warzone
497     Astronomic_497      Final Fantasy XIV
498    Delinquents_498         Moshi Monsters
499        Stealth_499                FIFA 16

[500 rows x 2 columns]

In [56]:
team_game_df.dtypes

team    object
game    object
dtype: object

### people-teams

In [57]:
nicks = generate_random(names_list, n=num_players)
nicks

['katherine_0',
 'jordan_1',
 'karen_2',
 'laura_3',
 'benjamin_4',
 'edward_5',
 'mark_6',
 'adam_7',
 'bryan_8',
 'laura_9',
 'peter_10',
 'peter_11',
 'arthur_12',
 'grace_13',
 'sharon_14',
 'vincent_15',
 'kayla_16',
 'jean_17',
 'arthur_18',
 'janice_19',
 'brandon_20',
 'charlotte_21',
 'jacqueline_22',
 'amanda_23',
 'nancy_24',
 'catherine_25',
 'kenneth_26',
 'patrick_27',
 'danielle_28',
 'jerry_29',
 'samantha_30',
 'evelyn_31',
 'joan_32',
 'christine_33',
 'christian_34',
 'alexander_35',
 'debra_36',
 'martha_37',
 'kyle_38',
 'eric_39',
 'kimberly_40',
 'tyler_41',
 'kathryn_42',
 'robert_43',
 'joe_44',
 'justin_45',
 'madison_46',
 'sandra_47',
 'eugene_48',
 'billy_49',
 'benjamin_50',
 'harold_51',
 'nicole_52',
 'marilyn_53',
 'carol_54',
 'christine_55',
 'zachary_56',
 'helen_57',
 'charles_58',
 'pamela_59',
 'terry_60',
 'bryan_61',
 'margaret_62',
 'austin_63',
 'brandon_64',
 'grace_65',
 'ashley_66',
 'melissa_67',
 'debra_68',
 'ruth_69',
 'megan_70',
 'nathan_71',
 'bobby_72',
 'carolyn_73',
 'adam_74',
 'cynthia_75',
 'shirley_76',
 'margaret_77',
 'ruth_78',
 'robert_79',
 'victoria_80',
 'maria_81',
 'tyler_82',
 'olivia_83',
 'christopher_84',
 'kathleen_85',
 'austin_86',
 'arthur_87',
 'heather_88',
 'joan_89',
 'adam_90',
 'kimberly_91',
 'alexis_92',
 'julie_93',
 'dorothy_94',
 'alexis_95',
 'austin_96',
 'pamela_97',
 'terry_98',
 'lauren_99',
 'jacqueline_100',
 'david_101',
 'thomas_102',
 'jesse_103',
 'jonathan_104',
 'grace_105',
 'vincent_106',
 'samuel_107',
 'robert_108',
 'gregory_109',
 'larry_110',
 'charles_111',
 'gary_112',
 'sara_113',
 'alexis_114',
 'deborah_115',
 'lawrence_116',
 'john_117',
 'ronald_118',
 'samantha_119',
 'karen_120',
 'gabriel_121',
 'jennifer_122',
 'tyler_123',
 'keith_124',
 'hannah_125',
 'kathryn_126',
 'kyle_127',
 'karen_128',
 'nathan_129',
 'ralph_130',
 'sophia_131',
 'raymond_132',
 'terry_133',
 'brittany_134',
 'brandon_135',
 'linda_136',
 'beverly_137',
 'cheryl_138',
 'elizabeth_139',
 'jordan_140',
 'michael_141',
 'natalie_142',
 'terry_143',
 'elijah_144',
 'amanda_145',
 'angela_146',
 'albert_147',
 'johnny_148',
 'gloria_149',
 'elizabeth_150',
 'laura_151',
 'elijah_152',
 'willie_153',
 'lisa_154',
 'william_155',
 'gary_156',
 'nicholas_157',
 'david_158',
 'alice_159',
 'gloria_160',
 'anthony_161',
 'russell_162',
 'russell_163',
 'sarah_164',
 'angela_165',
 'maria_166',
 'lauren_167',
 'kelly_168',
 'debra_169',
 'jean_170',
 'mary_171',
 'stephen_172',
 'louis_173',
 'dylan_174',
 'marie_175',
 'jose_176',
 'jack_177',
 'charles_178',
 'brenda_179',
 'patricia_180',
 'kenneth_181',
 'timothy_182',
 'cynthia_183',
 'amanda_184',
 'joe_185',
 'jeffrey_186',
 'grace_187',
 'stephanie_188',
 'laura_189',
 'christine_190',
 'andrew_191',
 'amanda_192',
 'arthur_193',
 'natalie_194',
 'anthony_195',
 'scott_196',
 'amber_197',
 'henry_198',
 'alexis_199',
 'walter_200',
 'eric_201',
 'albert_202',
 'patricia_203',
 'shirley_204',
 'scott_205',
 'donald_206',
 'carl_207',
 'susan_208',
 'arthur_209',
 'richard_210',
 'bryan_211',
 'russell_212',
 'kimberly_213',
 'dylan_214',
 'grace_215',
 'madison_216',
 'jacqueline_217',
 'nancy_218',
 'dennis_219',
 'brian_220',
 'kathleen_221',
 'betty_222',
 'karen_223',
 'timothy_224',
 'beverly_225',
 'frances_226',
 'alexander_227',
 'ashley_228',
 'carol_229',
 'kelly_230',
 'michael_231',
 'patrick_232',
 'shirley_233',
 'charlotte_234',
 'noah_235',
 'jennifer_236',
 'lisa_237',
 'emma_238',
 'ruth_239',
 'randy_240',
 'tyler_241',
 'peter_242',
 'terry_243',
 'julia_244',
 'marie_245',
 'jennifer_246',
 'amber_247',
 'jonathan_248',
 'william_249',
 'willie_250',
 'sarah_251',
 'megan_252',
 'kimberly_253',
 'charles_254',
 'sean_255',
 'shirley_256',
 'melissa_257',
 'helen_258',
 'bryan_259',
 'juan_260',
 'joan_261',
 'laura_262',
 'julia_263',
 'angela_264',
 'anthony_265',
 'carol_266',
 'lawrence_267',
 'jordan_268',
 'virginia_269',
 'zachary_270',
 'sharon_271',
 'albert_272',
 'william_273',
 'lawrence_274',
 'kimberly_275',
 'jean_276',
 'bobby_277',
 'justin_278',
 'shirley_279',
 'martha_280',
 'amy_281',
 'patrick_282',
 'danielle_283',
 'debra_284',
 'james_285',
 'henry_286',
 'justin_287',
 'charlotte_288',
 'elijah_289',
 'david_290',
 'jose_291',
 'janet_292',
 'terry_293',
 'sharon_294',
 'donna_295',
 'brian_296',
 'deborah_297',
 'zachary_298',
 'linda_299',
 'vincent_300',
 'laura_301',
 'arthur_302',
 'nicole_303',
 'juan_304',
 'donna_305',
 'joe_306',
 'noah_307',
 'judy_308',
 'noah_309',
 'jennifer_310',
 'larry_311',
 'willie_312',
 'cheryl_313',
 'brittany_314',
 'ronald_315',
 'amanda_316',
 'tyler_317',
 'gary_318',
 'jeremy_319',
 'patrick_320',
 'sharon_321',
 'rebecca_322',
 'janice_323',
 'janice_324',
 'beverly_325',
 'kathleen_326',
 'natalie_327',
 'kyle_328',
 'jack_329',
 'jordan_330',
 'rebecca_331',
 'madison_332',
 'brandon_333',
 'timothy_334',
 'lauren_335',
 'gregory_336',
 'rebecca_337',
 'isabella_338',
 'ryan_339',
 'jeremy_340',
 'carl_341',
 'paul_342',
 'harold_343',
 'madison_344',
 'paul_345',
 'kayla_346',
 'sarah_347',
 'henry_348',
 'christina_349',
 'donna_350',
 'stephen_351',
 'sophia_352',
 'james_353',
 'jose_354',
 'randy_355',
 'gabriel_356',
 'wayne_357',
 'kathleen_358',
 'ronald_359',
 'helen_360',
 'julia_361',
 'dylan_362',
 'eugene_363',
 'kayla_364',
 'kayla_365',
 'james_366',
 'roy_367',
 'jonathan_368',
 'ashley_369',
 'alexis_370',
 'paul_371',
 'adam_372',
 'gloria_373',
 'douglas_374',
 'andrew_375',
 'teresa_376',
 'kayla_377',
 'betty_378',
 'ronald_379',
 'terry_380',
 'megan_381',
 'beverly_382',
 'christina_383',
 'heather_384',
 'lawrence_385',
 'sean_386',
 'joe_387',
 'pamela_388',
 'sharon_389',
 'albert_390',
 'margaret_391',
 'zachary_392',
 'nancy_393',
 'mary_394',
 'mark_395',
 'pamela_396',
 'george_397',
 'russell_398',
 'hannah_399',
 'sarah_400',
 'martha_401',
 'theresa_402',
 'virginia_403',
 'stephen_404',
 'teresa_405',
 'pamela_406',
 'alice_407',
 'bobby_408',
 'kayla_409',
 'kevin_410',
 'jack_411',
 'jack_412',
 'martha_413',
 'dorothy_414',
 'barbara_415',
 'barbara_416',
 'thomas_417',
 'theresa_418',
 'douglas_419',
 'brandon_420',
 'bobby_421',
 'kenneth_422',
 'keith_423',
 'lisa_424',
 'andrew_425',
 'william_426',
 'katherine_427',
 'noah_428',
 'ethan_429',
 'juan_430',
 'angela_431',
 'austin_432',
 'louis_433',
 'kimberly_434',
 'nicholas_435',
 'kimberly_436',
 'terry_437',
 'debra_438',
 'jesse_439',
 'cheryl_440',
 'harold_441',
 'heather_442',
 'angela_443',
 'judy_444',
 'jerry_445',
 'jennifer_446',
 'judith_447',
 'arthur_448',
 'arthur_449',
 'denise_450',
 'amber_451',
 'carolyn_452',
 'george_453',
 'russell_454',
 'keith_455',
 'lauren_456',
 'danielle_457',
 'lawrence_458',
 'helen_459',
 'bryan_460',
 'eric_461',
 'rose_462',
 'timothy_463',
 'susan_464',
 'lawrence_465',
 'larry_466',
 'vincent_467',
 'kenneth_468',
 'rose_469',
 'sharon_470',
 'frances_471',
 'jack_472',
 'jerry_473',
 'karen_474',
 'isabella_475',
 'christina_476',
 'christian_477',
 'albert_478',
 'judy_479',
 'gregory_480',
 'nathan_481',
 'marie_482',
 'kimberly_483',
 'elizabeth_484',
 'evelyn_485',
 'karen_486',
 'mark_487',
 'jeremy_488',
 'doris_489',
 'tyler_490',
 'ethan_491',
 'bryan_492',
 'logan_493',
 'brandon_494',
 'bruce_495',
 'amy_496',
 'eugene_497',
 'jessica_498',
 'benjamin_499',
 'doris_500',
 'dylan_501',
 'samantha_502',
 'william_503',
 'bobby_504',
 'willie_505',
 'sarah_506',
 'kathryn_507',
 'maria_508',
 'carl_509',
 'dorothy_510',
 'juan_511',
 'barbara_512',
 'ethan_513',
 'gerald_514',
 'carl_515',
 'lauren_516',
 'vincent_517',
 'samuel_518',
 'pamela_519',
 'madison_520',
 'janice_521',
 'william_522',
 'jennifer_523',
 'dylan_524',
 'jordan_525',
 'melissa_526',
 'isabella_527',
 'ethan_528',
 'vincent_529',
 'amy_530',
 'douglas_531',
 'doris_532',
 'arthur_533',
 'lisa_534',
 'laura_535',
 'daniel_536',
 'kimberly_537',
 'christina_538',
 'roy_539',
 'lawrence_540',
 'jeffrey_541',
 'keith_542',
 'melissa_543',
 'joe_544',
 'sandra_545',
 'carl_546',
 'kathleen_547',
 'linda_548',
 'brandon_549',
 'aaron_550',
 'donna_551',
 'zachary_552',
 'george_553',
 'bobby_554',
 'theresa_555',
 'nicholas_556',
 'lawrence_557',
 'george_558',
 'janice_559',
 'jose_560',
 'terry_561',
 'julia_562',
 'stephanie_563',
 'keith_564',
 'adam_565',
 'abigail_566',
 'deborah_567',
 'richard_568',
 'jack_569',
 'jacqueline_570',
 'russell_571',
 'anna_572',
 'mary_573',
 'randy_574',
 'danielle_575',
 'ralph_576',
 'cynthia_577',
 'marie_578',
 'walter_579',
 'jose_580',
 'harold_581',
 'christina_582',
 'helen_583',
 'christian_584',
 'larry_585',
 'elizabeth_586',
 'michael_587',
 'louis_588',
 'sarah_589',
 'olivia_590',
 'olivia_591',
 'marie_592',
 'rebecca_593',
 'jordan_594',
 'gregory_595',
 'donald_596',
 'aaron_597',
 'marie_598',
 'andrea_599',
 'angela_600',
 'eric_601',
 'christian_602',
 'james_603',
 'teresa_604',
 'cheryl_605',
 'jason_606',
 'christopher_607',
 'david_608',
 'sarah_609',
 'gloria_610',
 'laura_611',
 'sean_612',
 'larry_613',
 'charles_614',
 'anna_615',
 'linda_616',
 'gary_617',
 'amber_618',
 'james_619',
 'margaret_620',
 'joyce_621',
 'diane_622',
 'jose_623',
 'kenneth_624',
 'sophia_625',
 'roger_626',
 'shirley_627',
 'gerald_628',
 'jason_629',
 'madison_630',
 'aaron_631',
 'ronald_632',
 'michael_633',
 'sara_634',
 'kimberly_635',
 'jennifer_636',
 'adam_637',
 'katherine_638',
 'nicholas_639',
 'kathryn_640',
 'jeremy_641',
 'jose_642',
 'theresa_643',
 'alexis_644',
 'donna_645',
 'evelyn_646',
 'william_647',
 'vincent_648',
 'olivia_649',
 'brenda_650',
 'judith_651',
 'steven_652',
 'victoria_653',
 'diana_654',
 'amanda_655',
 'dorothy_656',
 'hannah_657',
 'maria_658',
 'brandon_659',
 'judy_660',
 'brittany_661',
 'johnny_662',
 'ann_663',
 'andrew_664',
 'emily_665',
 'stephen_666',
 'joshua_667',
 'kathryn_668',
 'madison_669',
 'nicholas_670',
 'adam_671',
 'heather_672',
 'helen_673',
 'madison_674',
 'zachary_675',
 'frances_676',
 'katherine_677',
 'marie_678',
 'barbara_679',
 'michelle_680',
 'arthur_681',
 'thomas_682',
 'brandon_683',
 'jose_684',
 'alexis_685',
 'ryan_686',
 'jean_687',
 'edward_688',
 'thomas_689',
 'kayla_690',
 'frances_691',
 'thomas_692',
 'sophia_693',
 'betty_694',
 'austin_695',
 'hannah_696',
 'willie_697',
 'margaret_698',
 'julia_699',
 'teresa_700',
 'jacqueline_701',
 'pamela_702',
 'joshua_703',
 'rebecca_704',
 'willie_705',
 'richard_706',
 'catherine_707',
 'michael_708',
 'ethan_709',
 'ethan_710',
 'jean_711',
 'jacqueline_712',
 'emma_713',
 'janice_714',
 'marie_715',
 'ashley_716',
 'willie_717',
 'joseph_718',
 'janice_719',
 'arthur_720',
 'carolyn_721',
 'sara_722',
 'gerald_723',
 'beverly_724',
 'ralph_725',
 'aaron_726',
 'ryan_727',
 'eugene_728',
 'deborah_729',
 'jessica_730',
 'emma_731',
 'noah_732',
 'adam_733',
 'vincent_734',
 'helen_735',
 'james_736',
 'kevin_737',
 'douglas_738',
 'brandon_739',
 'edward_740',
 'nicholas_741',
 'scott_742',
 'timothy_743',
 'paul_744',
 'zachary_745',
 'judy_746',
 'vincent_747',
 'barbara_748',
 'alexander_749',
 'thomas_750',
 'judy_751',
 'grace_752',
 'adam_753',
 'madison_754',
 'carol_755',
 'abigail_756',
 'cheryl_757',
 'ryan_758',
 'susan_759',
 'stephanie_760',
 'alan_761',
 'jason_762',
 'joyce_763',
 'logan_764',
 'charles_765',
 'barbara_766',
 'danielle_767',
 'lauren_768',
 'angela_769',
 'paul_770',
 'larry_771',
 'carolyn_772',
 'julie_773',
 'anna_774',
 'nathan_775',
 'austin_776',
 'patrick_777',
 'dennis_778',
 'vincent_779',
 'sean_780',
 'lawrence_781',
 'sara_782',
 'willie_783',
 'pamela_784',
 'sara_785',
 'hannah_786',
 'rachel_787',
 'roy_788',
 'christian_789',
 'gloria_790',
 'kayla_791',
 'barbara_792',
 'andrew_793',
 'catherine_794',
 'henry_795',
 'robert_796',
 'eric_797',
 'frank_798',
 'bruce_799',
 'jason_800',
 'christian_801',
 'scott_802',
 'joyce_803',
 'brenda_804',
 'jose_805',
 'marilyn_806',
 'abigail_807',
 'olivia_808',
 'logan_809',
 'anthony_810',
 'gloria_811',
 'michelle_812',
 'juan_813',
 'elijah_814',
 'christopher_815',
 'diana_816',
 'judith_817',
 'joseph_818',
 'jennifer_819',
 'grace_820',
 'margaret_821',
 'stephen_822',
 'catherine_823',
 'janice_824',
 'frances_825',
 'lisa_826',
 'betty_827',
 'betty_828',
 'gary_829',
 'brittany_830',
 'melissa_831',
 'beverly_832',
 'john_833',
 'martha_834',
 'stephanie_835',
 'jesse_836',
 'joyce_837',
 'donna_838',
 'andrea_839',
 'marie_840',
 'rose_841',
 'christopher_842',
 'michelle_843',
 'daniel_844',
 'nicole_845',
 'shirley_846',
 'albert_847',
 'shirley_848',
 'judy_849',
 'timothy_850',
 'jordan_851',
 'benjamin_852',
 'scott_853',
 'karen_854',
 'alexander_855',
 'edward_856',
 'steven_857',
 'edward_858',
 'randy_859',
 'brian_860',
 'doris_861',
 'harold_862',
 'amanda_863',
 'frank_864',
 'noah_865',
 'gloria_866',
 'rose_867',
 'vincent_868',
 'justin_869',
 'anthony_870',
 'kimberly_871',
 'helen_872',
 'sarah_873',
 'ethan_874',
 'eric_875',
 'eugene_876',
 'nancy_877',
 'ethan_878',
 'william_879',
 'jose_880',
 'randy_881',
 'jacob_882',
 'gregory_883',
 'eugene_884',
 'eugene_885',
 'arthur_886',
 'douglas_887',
 'jordan_888',
 'debra_889',
 'arthur_890',
 'alexis_891',
 'terry_892',
 'shirley_893',
 'aaron_894',
 'joe_895',
 'adam_896',
 'joyce_897',
 'marilyn_898',
 'mark_899',
 'jennifer_900',
 'natalie_901',
 'arthur_902',
 'peter_903',
 'charlotte_904',
 'alan_905',
 'joshua_906',
 'marie_907',
 'jerry_908',
 'noah_909',
 'mary_910',
 'sara_911',
 'thomas_912',
 'frank_913',
 'charles_914',
 'austin_915',
 'jeffrey_916',
 'johnny_917',
 'janice_918',
 'adam_919',
 'kyle_920',
 'logan_921',
 'george_922',
 'isabella_923',
 'natalie_924',
 'henry_925',
 'aaron_926',
 'terry_927',
 'jeremy_928',
 'jeremy_929',
 'kyle_930',
 'ethan_931',
 'steven_932',
 'richard_933',
 'alexander_934',
 'shirley_935',
 'diane_936',
 'kimberly_937',
 'joyce_938',
 'justin_939',
 'joyce_940',
 'diana_941',
 'benjamin_942',
 'jeremy_943',
 'catherine_944',
 'kathleen_945',
 'james_946',
 'amy_947',
 'kathryn_948',
 'jessica_949',
 'marie_950',
 'frank_951',
 'joan_952',
 'teresa_953',
 'noah_954',
 'megan_955',
 'hannah_956',
 'michelle_957',
 'deborah_958',
 'victoria_959',
 'madison_960',
 'donald_961',
 'lauren_962',
 'samantha_963',
 'katherine_964',
 'zachary_965',
 'dorothy_966',
 'michelle_967',
 'james_968',
 'brian_969',
 'billy_970',
 'martha_971',
 'nathan_972',
 'maria_973',
 'daniel_974',
 'susan_975',
 'megan_976',
 'dylan_977',
 'julia_978',
 'virginia_979',
 'megan_980',
 'gary_981',
 'keith_982',
 'janice_983',
 'anthony_984',
 'brandon_985',
 'janice_986',
 'judy_987',
 'donald_988',
 'jacqueline_989',
 'james_990',
 'bryan_991',
 'roger_992',
 'andrea_993',
 'joseph_994',
 'marilyn_995',
 'scott_996',
 'nancy_997',
 'dennis_998',
 'jacqueline_999',
 ...]

In [58]:
team_game_df.team.sample(num_players, replace=True)

149             Sliders_149
194         Keep It 100_194
89               Mad Men_89
253    Men on a Mission_253
422        Mean Machine_422
               ...
74             Saboteurs_74
245               Colts_245
44              Slayers _44
41                 Venom_41
304             Wombats_304
Name: team, Length: 10000, dtype: object

In [59]:
people_team_df = pd.DataFrame({'nick': nicks}) 
# multiplying so that people are more than 1 team, playing different games
people_team_df['team'] = team_game_df.team.sample(people_team_df.shape[0], replace=True).to_list()
people_team_df

             nick                team
0     katherine_0        Matadors_159
1        jordan_1         Royalty_213
2         karen_2          United_116
3         laura_3         Slayers _44
4      benjamin_4     Code Black _343
...           ...                 ...
9995   diana_9995  Lethal Weapons_363
9996   brian_9996      Hillbillies_73
9997    paul_9997           Fuego_358
9998  rachel_9998          Zephyrs_25
9999   diane_9999         Pirates_349

[10000 rows x 2 columns]

In [60]:
people_team_df.dtypes

nick    object
team    object
dtype: object

### people-team-game

In [61]:
people_team_game_df = people_team_df.merge(team_game_df, on=['team'], how='left')
people_team_game_df

             nick                team                          game
0     katherine_0        Matadors_159           Black Desert Online
1        jordan_1         Royalty_213  Star Wars Jedi: Fallen Order
2         karen_2          United_116               The Sims Social
3         laura_3         Slayers _44                 Battlefield 4
4      benjamin_4     Code Black _343       Puyopuyo!! Quest Arcade
...           ...                 ...                           ...
9995   diana_9995  Lethal Weapons_363                       FIFA 18
9996   brian_9996      Hillbillies_73                  Blade & Soul
9997    paul_9997           Fuego_358                      Among Us
9998  rachel_9998          Zephyrs_25                     CrossFire
9999   diane_9999         Pirates_349                  Blade & Soul

[10000 rows x 3 columns]

In [62]:
# write players df to disk

people_team_game_df.to_csv('data/people_team_game.csv', index=False)

### datetimes

In [63]:
def pp(start: datetime, end: datetime, n: int):
    # based on https://stackoverflow.com/questions/50559078/generating-random-dates-within-a-given-range-in-pandas
    start_u = int(start.timestamp())
    end_u = int(end.timestamp())
    return pd.DatetimeIndex((np.random.randint(start_u, end_u, n, dtype=np.int64)).view('M8[s]'))

In [64]:
now = datetime.utcnow()
one_year_ago = datetime.utcnow() - timedelta(days=365)

pp(start=one_year_ago, end=now, n=100)

DatetimeIndex(['2020-10-30 06:57:05', '2021-04-02 14:01:49',
               '2020-08-25 04:21:22', '2021-04-11 23:09:51',
               '2020-12-07 20:35:49', '2021-03-25 20:12:25',
               '2020-07-14 01:38:23', '2020-06-15 20:36:59',
               '2020-12-02 06:45:08', '2021-05-29 16:16:55',
               '2021-04-05 11:59:57', '2021-05-19 19:22:23',
               '2020-08-27 04:22:55', '2021-02-03 23:03:17',
               '2021-04-01 18:13:39', '2020-12-21 23:39:52',
               '2021-05-19 21:53:57', '2021-04-18 12:39:44',
               '2020-09-16 10:57:33', '2020-12-10 15:56:48',
               '2020-10-21 18:26:18', '2020-10-13 09:09:29',
               '2020-06-18 15:42:36', '2021-02-16 19:35:24',
               '2020-08-26 09:12:17', '2020-09-03 03:49:24',
               '2021-05-24 05:43:55', '2020-06-29 10:44:55',
               '2020-07-15 10:48:47', '2020-11-08 11:27:40',
               '2020-09-17 23:12:44', '2021-03-23 11:55:53',
               '2020-08-06 19:17:37', '2020-06-30 23:22:47',
               '2020-12-02 09:34:22', '2020-10-16 09:31:02',
               '2021-04-24 08:28:34', '2020-08-14 05:12:34',
               '2020-07-30 02:25:50', '2021-04-18 06:06:11',
               '2020-08-22 12:52:34', '2020-09-13 16:42:04',
               '2021-01-24 11:30:06', '2020-11-03 23:09:29',
               '2020-07-14 22:28:25', '2021-04-05 10:21:48',
               '2020-07-07 01:36:34', '2021-03-28 16:51:16',
               '2021-05-04 15:13:07', '2020-10-09 15:22:45',
               '2020-09-18 13:42:55', '2021-02-01 23:04:45',
               '2021-03-19 15:53:48', '2020-08-12 12:18:38',
               '2020-09-09 16:09:33', '2020-08-14 01:02:31',
               '2020-09-06 19:54:36', '2020-11-19 14:46:41',
               '2021-05-25 05:13:43', '2020-11-06 05:03:05',
               '2021-02-22 22:45:19', '2020-10-29 20:36:44',
               '2020-12-02 18:15:52', '2021-03-29 21:52:58',
               '2021-04-01 06:16:24', '2020-09-25 17:39:16',
               '2020-09-19 01:15:46', '2021-05-10 01:04:03',
               '2020-09-29 17:24:43', '2021-04-15 05:00:53',
               '2020-10-29 01:12:15', '2020-11-04 03:23:27',
               '2020-08-20 06:15:21', '2020-10-19 06:58:13',
               '2021-03-23 18:48:15', '2020-10-04 02:21:06',
               '2020-09-30 02:26:41', '2021-05-29 08:41:45',
               '2020-08-05 12:43:22', '2020-11-09 08:40:11',
               '2020-12-05 15:54:56', '2021-01-18 13:43:36',
               '2020-09-02 14:50:12', '2020-12-20 22:47:25',
               '2020-10-16 01:52:11', '2020-06-14 15:17:36',
               '2021-04-15 21:09:53', '2020-07-03 17:22:01',
               '2021-01-07 03:42:51', '2020-07-03 03:57:38',
               '2020-11-15 18:58:09', '2020-12-29 16:35:45',
               '2020-07-18 22:31:09', '2021-05-11 17:29:29',
               '2020-09-22 21:40:44', '2021-05-08 04:28:41',
               '2020-08-08 19:52:01', '2020-12-07 13:48:03',
               '2021-01-05 05:14:10', '2020-12-05 15:19:07'],
              dtype='datetime64[ns]', freq=None)

### gameplays

In [65]:
num_games = 1000000

gameplays_df = people_team_game_df.sample(num_games, replace=True)
gameplays_df['datetime'] = pp(start=one_year_ago, end=now, n=num_games)
gameplays_df['score'] = (np.exp(np.random.normal(loc=5, scale=1, size=num_games)) + 1).astype(int)
gameplays_df

,nick,team,game,datetime,score
5631,billy_5631,Shock and Awe_219,FIFA 19,2020-11-25 12:19:07,1456
7608,brian_7608,Spartans_170,Fortnite,2021-03-25 17:36:16,123
2051,helen_2051,White Collars_311,Free Realms,2021-02-26 07:47:57,628
3522,theresa_3522,Otters_324,Call of Duty: Warzone,2021-06-12 22:39:52,83
2534,catherine_2534,Otters_324,Call of Duty: Warzone,2021-01-18 02:23:49,80
...,...,...,...,...,...
9431,dylan_9431,Magicians_452,Rocket League,2021-03-01 08:38:09,56
508,maria_508,Cupcakes_281,FIFA 18,2020-09-24 03:15:49,69
8553,richard_8553,Red Bulls_430,osu!,2021-05-26 16:40:14,126
2021,joyce_2021,White Collars_155,FIFA 19,2021-06-08 04:42:14,52
1529,christopher_1529,Rampage_237,Westward Journey Online II,2021-03-01 22:40:21,93

In [66]:
[(q, gameplays_df.score.quantile(q)) for q in np.linspace(0, 1, 11)]

[(0.0, 1.0),
 (0.1, 42.0),
 (0.2, 65.0),
 (0.30000000000000004, 88.0),
 (0.4, 116.0),
 (0.5, 149.0),
 (0.6000000000000001, 192.0),
 (0.7000000000000001, 252.0),
 (0.8, 345.0),
 (0.9, 536.0),
 (1.0, 17622.0)]

In [72]:
[(q, gameplays_df.datetime.quantile(q)) for q in np.linspace(0, 1, 11)]

[(0.0, Timestamp('2020-06-14 10:46:31')),
 (0.1, Timestamp('2020-07-20 18:05:23.400000')),
 (0.2, Timestamp('2020-08-26 09:52:34.800000')),
 (0.30000000000000004, Timestamp('2020-10-01 20:46:35.300000')),
 (0.4, Timestamp('2020-11-07 11:55:45.200000')),
 (0.5, Timestamp('2020-12-13 21:23:53.500000')),
 (0.6000000000000001, Timestamp('2021-01-19 06:43:31.600000')),
 (0.7000000000000001, Timestamp('2021-02-24 18:42:54.600000')),
 (0.8, Timestamp('2021-04-02 09:50:54')),
 (0.9, Timestamp('2021-05-08 22:23:43.300000')),
 (1.0, Timestamp('2021-06-14 10:44:52'))]

In [69]:
gameplays_df.datetime.min()

Timestamp('2020-06-14 10:46:31')

In [70]:
gameplays_df.datetime.max()

Timestamp('2021-06-14 10:44:52')

In [78]:
gameplays_df.sort_values(by='datetime')

,nick,team,game,datetime,score
252,megan_252,Vigilantes_136,FarmVille 2,2020-06-14 10:46:31,18
9663,billy_9663,Rockers_290,Fortnite,2020-06-14 10:48:19,158
5090,mark_5090,Darkside_453,Sudden Attack,2020-06-14 10:49:13,105
9249,melissa_9249,Praise Cheeses_51,Dofus,2020-06-14 10:49:26,72
5598,jessica_5598,Rip Tide_258,Ragnarok Online,2020-06-14 10:49:31,40
...,...,...,...,...,...
7200,juan_7200,Pirates_349,Blade & Soul,2021-06-14 10:42:38,440
2374,bobby_2374,Ghost Riders _8,Microsoft Solitaire,2021-06-14 10:42:50,72
9631,jeffrey_9631,Arsenal_158,Lineage II,2021-06-14 10:44:00,413
2637,logan_2637,Destroyers_91,Robocraft,2021-06-14 10:44:05,667
7468,elizabeth_7468,Wanderers_226,Star Wars Jedi: Fallen Order,2021-06-14 10:44:52,80

In [159]:
gameplays_df.to_csv('gameplays.csv', index=False)

In [163]:
gameplays_df.to_json('gameplays.json', orient='records', lines=True) # generate ndjson